version: "3.7"

services:    
    db:
        image: mysql:8.0
        container_name: rdm-db
        ports:
        - "3306:3306"
        environment:
        MYSQL_ROOT_PASSWORD: ""
        MYSQL_DATABASE: ""
        MYSQL_USER: ""
        MYSQL_PASSWORD: ""
        TZ: Asia/Jakarta
        volumes:
        - ./mysql-data:/var/lib/mysql
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password --default-time-zone='+07:00'
    rdmapp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rdm-app
        ports:
            - "8089:80"
        volumes:
            - ./:/var/www/html
        restart: always
